language: python

install:
  - |
    pip install --upgrade pip
    pip install --egg pyenv
    export PATH=~/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    pyenv install $PYTHON_VERSION

os:       osx
language: generic
env:      PYTHON_VERSION=3.6.2

script:   true
