language: python

install:
  - |
    echo "Home is $HOME"
    pip install --upgrade pip
    pip install --egg pyenv
    export PATH=~/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    pyenv install $PYTHON_VERSION

os:       osx
language: generic
env:      PYTHON_VERSION=2.7.2

script:   true
