language: python

install:
  - |
    pip install --upgrade pip
    pip install --egg pyenv
    export PATH=~/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    pyenv install $PYTHON_VERSION
    pyenv global $PYTHON_VERSION
    pyenv shell $PYTHON_VERSION

os:       osx
language: generic
env:      PYTHON_VERSION=2.7.1

script:   pyenv versions
